##### Copyright 2019 The TensorFlow Authors.

In [1]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

In [2]:
#@title MIT License
#
# Copyright (c) 2017 François Chollet
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

# Text classification with TensorFlow Hub: Movie reviews

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://www.tensorflow.org/tutorials/keras/text_classification_with_hub"><img src="https://www.tensorflow.org/images/tf_logo_32px.png" />View on TensorFlow.org</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/keras/text_classification_with_hub.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/tensorflow/docs/blob/master/site/en/tutorials/keras/text_classification_with_hub.ipynb"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />View on GitHub</a>
  </td>
  <td>
    <a href="https://storage.googleapis.com/tensorflow_docs/docs/site/en/tutorials/keras/text_classification_with_hub.ipynb"><img src="https://www.tensorflow.org/images/download_logo_32px.png" />Download notebook</a>
  </td>
  <td>
    <a href="https://tfhub.dev/s?module-type=text-embedding"><img src="https://www.tensorflow.org/images/hub_logo_32px.png" />See TF Hub models</a>
  </td>
</table>

This notebook classifies movie reviews as *positive* or *negative* using the text of the review. This is an example of *binary*—or two-class—classification, an important and widely applicable kind of machine learning problem.

The tutorial demonstrates the basic application of transfer learning with [TensorFlow Hub](https://tfhub.dev) and Keras.

It uses the [IMDB dataset](https://www.tensorflow.org/api_docs/python/tf/keras/datasets/imdb) that contains the text of 50,000 movie reviews from the [Internet Movie Database](https://www.imdb.com/). These are split into 25,000 reviews for training and 25,000 reviews for testing. The training and testing sets are *balanced*, meaning they contain an equal number of positive and negative reviews. 

This notebook uses [`tf.keras`](https://www.tensorflow.org/guide/keras), a high-level API to build and train models in TensorFlow, and [`tensorflow_hub`](https://www.tensorflow.org/hub), a library for loading trained models from [TFHub](https://tfhub.dev) in a single line of code. For a more advanced text classification tutorial using `tf.keras`, see the [MLCC Text Classification Guide](https://developers.google.com/machine-learning/guides/text-classification/).

此筆記本使用評論文本將電影評論分類為*正面*或*負面*。 這是*二元*（或二分類）分類的示例，這是一種重要且廣泛應用的機器學習問題。

本教程演示了使用 [TensorFlow Hub](https://tfhub.dev) 和 Keras 進行遷移學習的基本應用。

它使用 [IMDB 數據集](https://www.tensorflow.org/api_docs/python/tf/keras/datasets/imdb)，其中包含來自 [Internet Movie Database](https:// www.imdb.com/）。 這些分為 25,000 條訓練評論和 25,000 條測試評論。 訓練集和測試集是*平衡*的，這意味著它們包含相同數量的正面和負面評論。

此筆記本使用 [`tf.keras`](https://www.tensorflow.org/guide/keras)，一種用於在 TensorFlow 中構建和訓練模型的高級 API，以及 [`tensorflow_hub`](https:// www.tensorflow.org/hub)，一個用於在單行代碼中從 [TFHub](https://tfhub.dev) 加載訓練模型的庫。 有關使用 `tf.keras` 的更高級文本分類教程，請參閱 [MLCC 文本分類指南](https://developers.google.com/machine-learning/guides/text-classification/)。

In [3]:
!pip install tensorflow-hub
!pip install tensorflow-datasets

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [4]:
import os
import numpy as np

import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_datasets as tfds

print("Version: ", tf.__version__)
print("Eager mode: ", tf.executing_eagerly())
print("Hub version: ", hub.__version__)
print("GPU is", "available" if tf.config.list_physical_devices("GPU") else "NOT AVAILABLE")

Version:  2.11.0
Eager mode:  True
Hub version:  0.13.0
GPU is NOT AVAILABLE


## Download the IMDB dataset

The IMDB dataset is available on [imdb reviews](https://www.tensorflow.org/datasets/catalog/imdb_reviews) or on [TensorFlow datasets](https://www.tensorflow.org/datasets). The following code downloads the IMDB dataset to your machine (or the colab runtime):

## 下載 IMDB 數據集

IMDB 數據集可在 [imdb 評論](https://www.tensorflow.org/datasets/catalog/imdb_reviews) 或 [TensorFlow 數據集](https://www.tensorflow.org/datasets) 上找到。 以下代碼將 IMDB 數據集下載到您的機器（或 colab 運行時）：

In [5]:
# Split the training set into 60% and 40% to end up with 15,000 examples
# for training, 10,000 examples for validation and 25,000 examples for testing.
train_data, validation_data, test_data = tfds.load(
    name="imdb_reviews", 
    split=('train[:60%]', 'train[60%:]', 'test'),
    as_supervised=True)

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Generating splits...:   0%|          | 0/3 [00:00<?, ? splits/s]

Generating train examples...: 0 examples [00:00, ? examples/s]

Shuffling /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0.incompleteEKRZFP/imdb_reviews-train.tfrecord…

Generating test examples...: 0 examples [00:00, ? examples/s]

Shuffling /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0.incompleteEKRZFP/imdb_reviews-test.tfrecord*…

Generating unsupervised examples...: 0 examples [00:00, ? examples/s]

Shuffling /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0.incompleteEKRZFP/imdb_reviews-unsupervised.t…

Dataset imdb_reviews downloaded and prepared to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0. Subsequent calls will reuse this data.


## Explore the data 

Let's take a moment to understand the format of the data. Each example is a sentence representing the movie review and a corresponding label. The sentence is not preprocessed in any way. The label is an integer value of either 0 or 1, where 0 is a negative review, and 1 is a positive review.

Let's print first 10 examples.

## 探索數據

讓我們花點時間了解一下數據的格式。 每個示例都是代表電影評論和相應標籤的句子。 該句子未以任何方式進行預處理。 標籤是 0 或 1 的整數值，其中 0 是負面評論，1 是正面評論。

讓我們打印前 10 個示例。

In [6]:
train_examples_batch, train_labels_batch = next(iter(train_data.batch(10)))
train_examples_batch

<tf.Tensor: shape=(10,), dtype=string, numpy=
array([b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it.",
       b'I have been known to fall asleep during films, but this is usually due to a combination of things including, really tired, being warm and comfortable on the sette and having just eaten a lot. However on this occasion I fell 

Let's also print the first 10 labels.

讓我們也打印前 10 個標籤。

In [7]:
train_labels_batch

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([0, 0, 0, 1, 1, 1, 0, 0, 0, 0])>

## Build the model

The neural network is created by stacking layers—this requires three main architectural decisions:

* How to represent the text?
* How many layers to use in the model?
* How many *hidden units* to use for each layer?

In this example, the input data consists of sentences. The labels to predict are either 0 or 1.

One way to represent the text is to convert sentences into embeddings vectors. Use a pre-trained text embedding as the first layer, which will have three advantages:

*   You don't have to worry about text preprocessing,
*   Benefit from transfer learning,
*   the embedding has a fixed size, so it's simpler to process.

For this example you use a **pre-trained text embedding model** from [TensorFlow Hub](https://tfhub.dev) called [google/nnlm-en-dim50/2](https://tfhub.dev/google/nnlm-en-dim50/2).

There are many other pre-trained text embeddings from TFHub that can be used in this tutorial:

* [google/nnlm-en-dim128/2](https://tfhub.dev/google/nnlm-en-dim128/2) - trained with the same NNLM architecture on the same data as [google/nnlm-en-dim50/2](https://tfhub.dev/google/nnlm-en-dim50/2), but with a larger embedding dimension. Larger dimensional embeddings can improve on your task but it may take longer to train your model.
* [google/nnlm-en-dim128-with-normalization/2](https://tfhub.dev/google/nnlm-en-dim128-with-normalization/2) - the same as [google/nnlm-en-dim128/2](https://tfhub.dev/google/nnlm-en-dim128/2), but with additional text normalization such as removing punctuation. This can help if the text in your task contains additional characters or punctuation.
* [google/universal-sentence-encoder/4](https://tfhub.dev/google/universal-sentence-encoder/4) - a much larger model yielding 512 dimensional embeddings trained with a deep averaging network (DAN) encoder.

And many more! Find more [text embedding models](https://tfhub.dev/s?module-type=text-embedding) on TFHub.

## 構建模型

神經網絡是通過堆疊層創建的——這需要三個主要的架構決策：

* 如何表示文本？
* 在模型中使用多少層？
* 每層要使用多少個*隱藏單元*？

在此示例中，輸入數據由句子組成。 要預測的標籤是 0 或 1。

表示文本的一種方法是將句子轉換為嵌入向量。 使用預訓練的文本嵌入作為第一層，這將具有三個優點：

* 您不必擔心文本預處理，
*受益於遷移學習，
* 嵌入具有固定大小，因此處理起來更簡單。

對於此示例，您使用 [TensorFlow Hub](https://tfhub.dev) 中名為 [google/nnlm-en-dim50/2](https://tfhub.dev) 的**預訓練文本嵌入模型** /google/nnlm-en-dim50/2)。

在本教程中可以使用來自 TFHub 的許多其他預訓練文本嵌入：

* [google/nnlm-en-dim128/2](https://tfhub.dev/google/nnlm-en-dim128/2) - 使用與 [google/nnlm-en- dim50/2](https://tfhub.dev/google/nnlm-en-dim50/2)，但嵌入維度更大。 更大維度的嵌入可以改進您的任務，但可能需要更長的時間來訓練您的模型。
* [google/nnlm-en-dim128-with-normalization/2](https://tfhub.dev/google/nnlm-en-dim128-with-normalization/2) - 與 [google/nnlm-en- dim128/2](https://tfhub.dev/google/nnlm-en-dim128/2)，但具有額外的文本規範化，例如刪除標點符號。 如果任務中的文本包含其他字符或標點符號，這會有所幫助。
* [google/universal-sentence-encoder/4](https://tfhub.dev/google/universal-sentence-encoder/4) - 一個更大的模型產生 512 維嵌入，使用深度平均網絡 (DAN) 編碼器訓練 .

還有很多！ 在 TFHub 上查找更多[文本嵌入模型](https://tfhub.dev/s?module-type=text-embedding)。

Let's first create a Keras layer that uses a TensorFlow Hub model to embed the sentences, and try it out on a couple of input examples. Note that no matter the length of the input text, the output shape of the embeddings is: `(num_examples, embedding_dimension)`.

讓我們首先創建一個使用 TensorFlow Hub 模型嵌入句子的 Keras 層，並在幾個輸入示例上進行嘗試。 請注意，無論輸入文本的長度如何，嵌入的輸出形狀都是：`(num_examples, embedding_dimension)`。

In [8]:
embedding = "https://tfhub.dev/google/nnlm-en-dim50/2"
hub_layer = hub.KerasLayer(embedding, input_shape=[], 
                           dtype=tf.string, trainable=True)
hub_layer(train_examples_batch[:3])

<tf.Tensor: shape=(3, 50), dtype=float32, numpy=
array([[ 0.5423195 , -0.0119017 ,  0.06337538,  0.06862972, -0.16776837,
        -0.10581174,  0.16865303, -0.04998824, -0.31148055,  0.07910346,
         0.15442263,  0.01488662,  0.03930153,  0.19772711, -0.12215476,
        -0.04120981, -0.2704109 , -0.21922152,  0.26517662, -0.80739075,
         0.25833532, -0.3100421 ,  0.28683215,  0.1943387 , -0.29036492,
         0.03862849, -0.7844411 , -0.0479324 ,  0.4110299 , -0.36388892,
        -0.58034706,  0.30269456,  0.3630897 , -0.15227164, -0.44391504,
         0.19462997,  0.19528408,  0.05666234,  0.2890704 , -0.28468323,
        -0.00531206,  0.0571938 , -0.3201318 , -0.04418665, -0.08550783,
        -0.55847436, -0.23336391, -0.20782952, -0.03543064, -0.17533456],
       [ 0.56338924, -0.12339553, -0.10862679,  0.7753425 , -0.07667089,
        -0.15752277,  0.01872335, -0.08169781, -0.3521876 ,  0.4637341 ,
        -0.08492756,  0.07166859, -0.00670817,  0.12686075, -0.19326553,
 

Let's now build the full model:

現在讓我們構建完整的模型：

In [9]:
model = tf.keras.Sequential()
model.add(hub_layer)
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dense(1))

model.summary()

Instructions for updating:
Lambda fuctions will be no more assumed to be used in the statement where they are used, or at least in the same block. https://github.com/tensorflow/tensorflow/issues/56089


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 keras_layer (KerasLayer)    (None, 50)                48190600  
                                                                 
 dense (Dense)               (None, 16)                816       
                                                                 
 dense_1 (Dense)             (None, 1)                 17        
                                                                 
Total params: 48,191,433
Trainable params: 48,191,433
Non-trainable params: 0
_________________________________________________________________


The layers are stacked sequentially to build the classifier:

1. The first layer is a TensorFlow Hub layer. This layer uses a pre-trained Saved Model to map a sentence into its embedding vector. The pre-trained text embedding model that you are using ([google/nnlm-en-dim50/2](https://tfhub.dev/google/nnlm-en-dim50/2)) splits the sentence into tokens, embeds each token and then combines the embedding. The resulting dimensions are: `(num_examples, embedding_dimension)`. For this NNLM model, the `embedding_dimension` is 50.
2. This fixed-length output vector is piped through a fully-connected (`Dense`) layer with 16 hidden units.
3. The last layer is densely connected with a single output node.

Let's compile the model.

這些層按順序堆疊以構建分類器：

1. 第一層是TensorFlow Hub層。 該層使用預訓練的保存模型將句子映射到其嵌入向量中。 您使用的預訓練文本嵌入模型 ([google/nnlm-en-dim50/2](https://tfhub.dev/google/nnlm-en-dim50/2)) 將句子拆分為標記，嵌入 每個標記，然後組合嵌入。 結果維度為：`(num_examples, embedding_dimension)`。 對於此 NNLM 模型，“embedding_dimension”為 50。
2. 這個固定長度的輸出向量通過具有 16 個隱藏單元的全連接（“密集”）層進行傳輸。
3. 最後一層與單個輸出節點密集連接。

讓我們編譯模型。

### Loss function and optimizer

A model needs a loss function and an optimizer for training. Since this is a binary classification problem and the model outputs logits (a single-unit layer with a linear activation), you'll use the `binary_crossentropy` loss function.

This isn't the only choice for a loss function, you could, for instance, choose `mean_squared_error`. But, generally, `binary_crossentropy` is better for dealing with probabilities—it measures the "distance" between probability distributions, or in our case, between the ground-truth distribution and the predictions.

Later, when you are exploring regression problems (say, to predict the price of a house), you'll see how to use another loss function called mean squared error.

Now, configure the model to use an optimizer and a loss function:

### 損失函數和優化器

一個模型需要一個損失函數和一個優化器來訓練。 由於這是一個二元分類問題並且模型輸出 logits（具有線性激活的單單元層），您將使用 `binary_crossentropy` 損失函數。

這不是損失函數的唯一選擇，例如，您可以選擇“mean_squared_error”。 但是，一般來說，`binary_crossentropy` 更適合處理概率——它測量概率分佈之間的“距離”，或者在我們的例子中，測量真實分佈與預測之間的“距離”。

稍後，當您探索回歸問題（例如，預測房屋價格）時，您將看到如何使用另一個稱為均方誤差的損失函數。

現在，配置模型以使用優化器和損失函數：

In [10]:
model.compile(optimizer='adam',
              loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              metrics=['accuracy'])

## Train the model

Train the model for 10 epochs in mini-batches of 512 samples. This is 10 iterations over all samples in the `x_train` and `y_train` tensors. While training, monitor the model's loss and accuracy on the 10,000 samples from the validation set:

## 訓練模型

在 512 個樣本的小批量中訓練模型 10 個時期。 這是對 `x_train` 和 `y_train` 張量中所有樣本的 10 次迭代。 訓練時，在驗證集中的 10,000 個樣本上監控模型的損失和準確性：

In [11]:
history = model.fit(train_data.shuffle(10000).batch(512),
                    epochs=10,
                    validation_data=validation_data.batch(512),
                    verbose=1)

Epoch 1/10
30/30 [==============================] - 42s 1s/step - loss: 0.6658 - accuracy: 0.5154 - val_loss: 0.6178 - val_accuracy: 0.5559
Epoch 2/10
30/30 [==============================] - 39s 1s/step - loss: 0.5545 - accuracy: 0.6626 - val_loss: 0.5103 - val_accuracy: 0.7286
Epoch 3/10
30/30 [==============================] - 41s 1s/step - loss: 0.4218 - accuracy: 0.8075 - val_loss: 0.4063 - val_accuracy: 0.8178
Epoch 4/10
30/30 [==============================] - 39s 1s/step - loss: 0.2995 - accuracy: 0.8826 - val_loss: 0.3427 - val_accuracy: 0.8466
Epoch 5/10
30/30 [==============================] - 41s 1s/step - loss: 0.2126 - accuracy: 0.9247 - val_loss: 0.3175 - val_accuracy: 0.8556
Epoch 6/10
30/30 [==============================] - 41s 1s/step - loss: 0.1548 - accuracy: 0.9481 - val_loss: 0.3077 - val_accuracy: 0.8648
Epoch 7/10
30/30 [==============================] - 40s 1s/step - loss: 0.1106 - accuracy: 0.9695 - val_loss: 0.3168 - val_accuracy: 0.8576
Epoch 8/10
30/30 [==

## Evaluate the model

And let's see how the model performs. Two values will be returned. Loss (a number which represents our error, lower values are better), and accuracy.

## 評估模型

讓我們看看模型的表現如何。 將返回兩個值。 損失（代表我們的錯誤的數字，值越低越好）和準確性。

In [12]:
results = model.evaluate(test_data.batch(512), verbose=2)

for name, value in zip(model.metrics_names, results):
  print("%s: %.3f" % (name, value))

49/49 - 10s - loss: 0.3604 - accuracy: 0.8546 - 10s/epoch - 207ms/step
loss: 0.360
accuracy: 0.855


This fairly naive approach achieves an accuracy of about 87%. With more advanced approaches, the model should get closer to 95%.

這種相當天真的方法達到了大約 87% 的準確率。 使用更高級的方法，模型應該接近 95%。

## Further reading

* For a more general way to work with string inputs and for a more detailed analysis of the progress of accuracy and loss during training, see the [Text classification with preprocessed text](./text_classification.ipynb) tutorial.
* Try out more [text-related tutorials](https://www.tensorflow.org/hub/tutorials#text-related-tutorials) using trained models from TFHub.

## 延伸閱讀

* 有關使用字符串輸入的更一般方法以及對訓練期間準確性和損失的進展的更詳細分析，請參閱[使用預處理文本進行文本分類](./text_classification.ipynb) 教程。
* 使用來自 TFHub 的訓練模型嘗試更多[文本相關教程](https://www.tensorflow.org/hub/tutorials#text-related-tutorials)。